version: '3.8'

services:
    mysql_db:
        image: mysql:8.0.21
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db_allocation
            MYSQL_USER: mysql_user
            MYSQL_PASSWORD: mysql_password
        ports:
            - 3306:3306
    
    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080
        depends_on:
            - mysql_db

    server:
        build:
            context: ./
        restart: always
        ports:
            - 8080:8080
            - 5005:5005
        depends_on:
            - mysql_db
        command: ./run.sh
        volumes:
            - ./:/professor-allocation
